### ISSUE TITLE
Gradle failure only when attempting to generate flavor release build.

### ISSUE THREAD

**Issue by dsspence** [moallemi/gradle-advanced-build-version#8]
Debug build compiles with no issues.  Only release build fails.  If I remove the advanced versioning code, release will succeed.

Is this a groovy dependency or class path issue?

Caused by: java.lang.NullPointerException: Cannot invoke method canRead() on null object
11:52:54.312 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.moallemi.gradle.AdvancedBuildVersionPlugin$_apply_closure1.doCall(AdvancedBuildVersionPlugin.groovy:24)
11:52:54.313 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
11:52:54.315 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
11:52:54.316 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
11:52:54.317 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
11:52:54.317 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
11:52:54.318 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
11:52:54.319 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)

Thanks.

**Comment by dsspence** [comment]
I guess it is looking for a version.properties file but I'm not using AUTO_INCREMENT_ONE_STEP, I'm using org.moallemi.gradle.internal.VersionCodeType.DATE.

**Comment by dsspence** [comment]
Moved the line :

apply plugin: 'org.moallemi.advanced-build-version'

from the project build.gradle to the app's build.gradle and now release build types succeed.

**Comment by nex0s** [comment]
Hi,

I still have the problem:
codeOptions is commented so I guess it should not look for the property file and thus not crash.

Error:A problem occurred configuring project ':app'.
> Cannot invoke method canRead() on null object

Stacktrace:
Caused by: java.lang.NullPointerException: Cannot invoke method canRead() on null object
        at org.moallemi.gradle.AdvancedBuildVersionPlugin$_apply_closure1.doCall(AdvancedBuildVersionPlugin.groovy:27)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy10.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
        ... 41 more
